server:
  port: 9997
spring:
  application:
    name: zuul-service
  # security:
  #   user:
  #     name: 'admin'
  #     password: 'admin'
  # rabbitmq:
  #   host: 172.18.55.204
  #   port: 5672
  #   username: admin
  #   password: admin
  #   virtual-host: sleuth
zuul:
  routes:
    account-API:
      path: /account*/**
      serviceId: account
      strip-prefix: false #必须设置为false，否则zuul代码中回将path截取，导致访问404
    access-API:
      path: /access*/**
      serviceId: access-control
      strip-prefix: false #必须设置为false，否则zuul代码中回将path截取，导致访问404
    factory-API:
      path: /factory*/**
      serviceId: factory-model
      strip-prefix: false #必须设置为false，否则zuul代码中回将path截取，导致访问404
    dynamic-API:
      path: /dynamic*/**
      serviceId: dynamicentity
      strip-prefix: false #必须设置为false，否则zuul代码中回将path截取，导致访问404
    kernal-API:
      path: /kernal*/**
      serviceId: kernal
      strip-prefix: false #必须设置为false，否则zuul代码中回将path截取，导致访问404
    misc-API:
      path: /misc*/**
      serviceId: misc
      strip-prefix: false #必须设置为false，否则zuul代码中回将path截取，导致访问404
    plugin-API:
      path: /plugin*/**
      serviceId: plugin
      strip-prefix: false #必须设置为false，否则zuul代码中回将path截取，导致访问404
    process-API:
      path: /process*/**
      serviceId: process
      strip-prefix: false #必须设置为false，否则zuul代码中回将path截取，导致访问404
    product-API:
      path: /product*/**
      serviceId: product
      strip-prefix: false #必须设置为false，否则zuul代码中回将path截取，导致访问404
    tracking-API:
      path: /tracking*/**
      serviceId: tracking
      strip-prefix: false #必须设置为false，否则zuul代码中回将path截取，导致访问404
    work-API:
      path: /work*/**
      serviceId: work-calendar
      strip-prefix: false #必须设置为false，否则zuul代码中回将path截取，导致访问404
    state-API:
      path: /stateModel*/**
      serviceId: state-model
      strip-prefix: false #必须设置为false，否则zuul代码中回将path截取，导致访问404
    job-API:
      path: /job*/**
      serviceId: job
      strip-prefix: false #必须设置为false，否则zuul代码中回将path截取，导致访问404



  # host:
  #   connect-timeout-millis: 10000
  #   socket-timeout-millis: 60000


# ribbon:
#   ReadTimeout: 60000
#   ConnectTimeout: 60000


# eureka:
#   instance:
#     prefer-ip-address: true