server:
  port: 10013
eruke:
  instance:
    status-page-url: http://172.18.96.89:${server.port}/swagger-ui.html
spring:
  application:
    name: tracking
#文件服务器，模板地址文件夹
file-template-server: http://172.18.55.201:3000/file/template/