server:
  port: 10013

spring:
  application:
    name: tracking

eruke:
  instance:
    status-page-url: http://172.18.37.41:${server.port}/swagger-ui.html
    
#文件服务器，模板地址文件夹
file-template-server: http://172.18.55.201:3000/file/template/    
