server:
  port: 8761
spring:
  application:
    name: service-hub
  cloud:
    config:
      discovery:
        enabled: true
#  profiles: slaveA
eureka:
  client:
    registerWithEureka: false   
    fetchRegistry: false

  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
